from typing import Optional

from BaseClasses import Item, ItemClassification


class MonsterSanctuaryItem(Item):
    game: str = "Monster Sanctuary"


class ItemDef:
    def __init__(self, id: Optional[int], name: str, classification: ItemClassification, count: int = 1):
        self.id = id
        self.name = name
        self.classification = classification
        self.count = count


item_table: list[ItemDef] = [
    ItemDef(69000, "100 G", ItemClassification.filler, count=1),
    ItemDef(69001, "150 G", ItemClassification.filler, count=1),
    ItemDef(69002, "250 G", ItemClassification.filler, count=1),
    ItemDef(69003, "400 G", ItemClassification.filler, count=1),
    ItemDef(69004, "500 G", ItemClassification.filler, count=1),
    ItemDef(69005, "1000 G", ItemClassification.filler, count=1),
    ItemDef(69006, "1500 G", ItemClassification.filler, count=1),
    ItemDef(69007, "2000 G", ItemClassification.filler, count=1),
    ItemDef(69008, "2500 G", ItemClassification.filler, count=1),
    ItemDef(69009, "3000 G", ItemClassification.filler, count=1),
    ItemDef(69010, "4000 G", ItemClassification.filler, count=1),
    ItemDef(69011, "5000 G", ItemClassification.filler, count=1),
    ItemDef(69012, "Almond", ItemClassification.filler, count=1),
    ItemDef(69013, "Banana", ItemClassification.filler, count=1),
    ItemDef(69014, "Blue Gem", ItemClassification.filler, count=1),
    ItemDef(69015, "Bronze", ItemClassification.filler, count=1),
    ItemDef(69016, "Carrot", ItemClassification.filler, count=1),
    ItemDef(69017, "Clear Stone", ItemClassification.filler, count=1),
    ItemDef(69018, "Cocoon", ItemClassification.filler, count=1),
    ItemDef(69019, "Cookie Mushroom", ItemClassification.filler, count=1),
    ItemDef(69020, "Copper", ItemClassification.filler, count=1),
    ItemDef(69021, "Corn", ItemClassification.filler, count=1),
    ItemDef(69022, "Cotton", ItemClassification.filler, count=1),
    ItemDef(69023, "Craft Box", ItemClassification.filler, count=1),
    ItemDef(69024, "Crimson Gem", ItemClassification.filler, count=1),
    ItemDef(69025, "Crystal Chard", ItemClassification.filler, count=1),
    ItemDef(69026, "Crystal Shard", ItemClassification.filler, count=1),
    ItemDef(69027, "Emerald", ItemClassification.filler, count=1),
    ItemDef(69028, "Gold", ItemClassification.filler, count=1),
    ItemDef(69029, "Grapes", ItemClassification.filler, count=1),
    ItemDef(69030, "Green Gem", ItemClassification.filler, count=1),
    ItemDef(69031, "Grey Pearl", ItemClassification.filler, count=1),
    ItemDef(69032, "Hazelnut", ItemClassification.filler, count=1),
    ItemDef(69033, "Hide", ItemClassification.filler, count=1),
    ItemDef(69034, "Iron", ItemClassification.filler, count=1),
    ItemDef(69035, "Leather", ItemClassification.filler, count=1),
    ItemDef(69036, "Linen", ItemClassification.filler, count=1),
    ItemDef(69037, "Mango", ItemClassification.filler, count=1),
    ItemDef(69038, "Orange", ItemClassification.filler, count=1),
    ItemDef(69039, "Peanut", ItemClassification.filler, count=1),
    ItemDef(69040, "Pear", ItemClassification.filler, count=1),
    ItemDef(69041, "Raw Hide", ItemClassification.filler, count=1),
    ItemDef(69042, "Red Gem", ItemClassification.filler, count=1),
    ItemDef(69043, "Ruby", ItemClassification.filler, count=1),
    ItemDef(69044, "Sapphire", ItemClassification.filler, count=1),
    ItemDef(69045, "Shift Stone", ItemClassification.filler, count=1),
    ItemDef(69046, "Silk", ItemClassification.filler, count=1),
    ItemDef(69047, "Silver", ItemClassification.filler, count=1),
    ItemDef(69048, "Steel", ItemClassification.filler, count=1),
    ItemDef(69049, "Strawberry", ItemClassification.filler, count=1),
    ItemDef(69050, "Switch Stone", ItemClassification.filler, count=1),
    ItemDef(69051, "Verdant Gem", ItemClassification.filler, count=1),
    ItemDef(69052, "Volcanic Ash", ItemClassification.filler, count=1),
    ItemDef(69053, "Walnut", ItemClassification.filler, count=1),
    ItemDef(69054, "Wool", ItemClassification.filler, count=1),
    ItemDef(69055, "Big Potion", ItemClassification.useful, count=1),
    ItemDef(69056, "Combo Potion", ItemClassification.useful, count=1),
    ItemDef(69057, "Mass Antidote", ItemClassification.useful, count=1),
    ItemDef(69058, "Mass Potion", ItemClassification.useful, count=1),
    ItemDef(69059, "Mega Potion", ItemClassification.useful, count=1),
    ItemDef(69060, "Phoenix Serum", ItemClassification.useful, count=1),
    ItemDef(69061, "Phoenix Tear", ItemClassification.useful, count=1),
    ItemDef(69062, "Potion", ItemClassification.useful, count=1),
    ItemDef(69063, "Skill Potion", ItemClassification.useful, count=1),
    ItemDef(69064, "Skill Resetter", ItemClassification.useful, count=1),
    ItemDef(69065, "Smoke Bomb", ItemClassification.useful, count=1),
    ItemDef(69066, "Bandana", ItemClassification.useful, count=1),
    ItemDef(69067, "Belt", ItemClassification.useful, count=1),
    ItemDef(69068, "Bracelet", ItemClassification.useful, count=1),
    ItemDef(69069, "Bracer", ItemClassification.useful, count=1),
    ItemDef(69070, "Cape", ItemClassification.useful, count=1),
    ItemDef(69071, "Cestus", ItemClassification.useful, count=1),
    ItemDef(69072, "Claws", ItemClassification.useful, count=1),
    ItemDef(69073, "Coat", ItemClassification.useful, count=1),
    ItemDef(69074, "Crit Ring", ItemClassification.useful, count=1),
    ItemDef(69075, "Diadem", ItemClassification.useful, count=1),
    ItemDef(69076, "Fang", ItemClassification.useful, count=1),
    ItemDef(69077, "Feather", ItemClassification.useful, count=1),
    ItemDef(69078, "Gauntlet", ItemClassification.useful, count=1),
    ItemDef(69079, "Helmet", ItemClassification.useful, count=1),
    ItemDef(69080, "Hood", ItemClassification.useful, count=1),
    ItemDef(69081, "Impact Ring", ItemClassification.useful, count=1),
    ItemDef(69082, "Katar", ItemClassification.useful, count=1),
    ItemDef(69083, "Kunai", ItemClassification.useful, count=1),
    ItemDef(69084, "Large Shield", ItemClassification.useful, count=1),
    ItemDef(69085, "Mana Ring", ItemClassification.useful, count=1),
    ItemDef(69086, "Morning Star", ItemClassification.useful, count=1),
    ItemDef(69087, "Needle", ItemClassification.useful, count=1),
    ItemDef(69088, "Orb", ItemClassification.useful, count=1),
    ItemDef(69089, "Ribbon", ItemClassification.useful, count=1),
    ItemDef(69090, "Scroll", ItemClassification.useful, count=1),
    ItemDef(69091, "Shell", ItemClassification.useful, count=1),
    ItemDef(69092, "Shuriken", ItemClassification.useful, count=1),
    ItemDef(69093, "Staff", ItemClassification.useful, count=1),
    ItemDef(69094, "Sustain Ring", ItemClassification.useful, count=1),
    ItemDef(69095, "Tome", ItemClassification.useful, count=1),
    ItemDef(69096, "Vital Ring", ItemClassification.useful, count=1),
    ItemDef(69097, "Wizard Hat", ItemClassification.useful, count=1),
    ItemDef(69098, "Buckler", ItemClassification.useful, count=1),
    ItemDef(69099, "Dungeon Explorer", ItemClassification.useful, count=1),
    ItemDef(69100, "Fan", ItemClassification.useful, count=1),
    ItemDef(69101, "Flute", ItemClassification.useful, count=1),
    ItemDef(69102, "Harp", ItemClassification.useful, count=1),
    ItemDef(69103, "Hexing Rod", ItemClassification.useful, count=1),
    ItemDef(69104, "Katana", ItemClassification.useful, count=1),
    ItemDef(69105, "Key of Power", ItemClassification.progression, count=1),
    ItemDef(69106, "Lightning Sphere", ItemClassification.useful, count=1),
    ItemDef(69107, "Mage Flask", ItemClassification.useful, count=1),
    ItemDef(69108, "Memorial Ring", ItemClassification.useful, count=1),
    ItemDef(69109, "Moon Sword", ItemClassification.useful, count=1),
    ItemDef(69110, "Ocarina", ItemClassification.useful, count=1),
    ItemDef(69111, "Old World Tycoon", ItemClassification.useful, count=1),
    ItemDef(69112, "Omni Ring", ItemClassification.useful, count=1),
    ItemDef(69113, "Pandora's Box", ItemClassification.useful, count=1),
    ItemDef(69114, "Purifying Mace", ItemClassification.useful, count=1),
    ItemDef(69115, "Restoring Wand", ItemClassification.useful, count=1),
    ItemDef(69116, "Scepter", ItemClassification.useful, count=1),
    ItemDef(69117, "Scythe", ItemClassification.useful, count=1),
    ItemDef(69118, "Summoned Sword", ItemClassification.useful, count=1),
    ItemDef(69119, "Torch", ItemClassification.useful, count=1),
    ItemDef(69120, "Warhorn", ItemClassification.useful, count=1),
    ItemDef(69121, "Warrior Flask", ItemClassification.useful, count=1),
    ItemDef(69122, "Ancestral Medal", ItemClassification.useful, count=1),
    ItemDef(69123, "Blood Vessel", ItemClassification.useful, count=1),
    ItemDef(69124, "Infinity Flame", ItemClassification.useful, count=1),
    ItemDef(69125, "Silver Feather", ItemClassification.useful, count=1),
    ItemDef(69126, "Celestial Feather", ItemClassification.progression, count=1),
    ItemDef(69127, "Runestone Shard", ItemClassification.useful, count=1),
    ItemDef(69128, "Sun Stone", ItemClassification.useful, count=1),
    ItemDef(69129, "Double Jump Boots", ItemClassification.progression, count=1),
    ItemDef(69130, "Ancient Woods Key", ItemClassification.progression, count=3),
    ItemDef(69131, "Blue Caves Key", ItemClassification.progression, count=3),
    ItemDef(69132, "Magma Chamber Key", ItemClassification.progression, count=2),
    ItemDef(69133, "Mystical Workshop Key", ItemClassification.progression, count=3),
    ItemDef(69134, "Stronghold Dungeon Key", ItemClassification.progression, count=2),
    ItemDef(69135, "Underworld Key", ItemClassification.progression, count=1),
    ItemDef(69136, "Reward Box lvl 1", ItemClassification.useful, count=1),
    ItemDef(69137, "Reward Box lvl 2", ItemClassification.useful, count=1),
    ItemDef(69138, "Reward Box lvl 3", ItemClassification.useful, count=1),
    ItemDef(69139, "Reward Box lvl 4", ItemClassification.useful, count=1),
    ItemDef(69140, "Sanctuary Token", ItemClassification.progression, count=1),
    ItemDef(69141, "Azure Gem", ItemClassification.filler, count=1),
    ItemDef(69142, "Level Badge", ItemClassification.filler, count=1),
    ItemDef(69143, "Lucky Clover", ItemClassification.useful, count=1),
    ItemDef(69144, "Medallion", ItemClassification.progression, count=1),
    ItemDef(69145, "Rare Seashell", ItemClassification.progression, count=1),
    ItemDef(69146, "Raspberry", ItemClassification.filler, count=1),
    ItemDef(69147, "Slime Skin", ItemClassification.useful, count=1),
    ItemDef(69148, "Monster Bell", ItemClassification.filler, count=1),
    ItemDef(69149, "Dragon Lord", ItemClassification.useful, count=1),
    ItemDef(69150, "Mountain Path Key", ItemClassification.progression, count=1),
]

item_name_to_id = {item.name: item.id for item in item_table}
item_name_groups = {
    "filler": [item.name for item in item_table if item.classification == ItemClassification.filler],
    "useful": [item.name for item in item_table if item.classification == ItemClassification.useful],
    "progression": [item.name for item in item_table if item.classification == ItemClassification.progression]
}
