from typing import Optional

from BaseClasses import Location

class MonsterSantuaryLocation(Location):
    game: str = "Monster Santuary"


class LocationDef:
    def __init__(self, id: Optional[int], name: str, region: str):
        self.id = id
        self.name = name
        self.region = region


location_table: list[LocationDef] = [
    LocationDef(4560001, '(MP) Tutorial Chest on Ground','Mountain Path'),
    LocationDef(4560002, '(MP) Tutorial Chest on Lower Ledge','Mountain Path'),
    LocationDef(4560003, '(MP) Tutorial Chest on Upper Ledge','Mountain Path'),
    LocationDef(4560004, '(MP) Tutorial Chest Behind Breakable Wall','Mountain Path'),
    LocationDef(4560005, '(MP) Manicorb Overlook Room Top Chest','Mountain Path'),
    LocationDef(4560006, '(MP) Manicorb Overlook Room Middle Chest','Mountain Path'),
    LocationDef(4560007, '(MP) Manicorb Overlook Room Bottom Chest','Mountain Path'),
    LocationDef(4560008, '(MP) Chest Above Monolith','Mountain Path'),
    LocationDef(4560009, '(MP) In Hole Chest (1)','Mountain Path'),
    LocationDef(4560010, '(MP) In Hole Chest (2)','Mountain Path'),
    LocationDef(4560011, '(MP) Wall Warp Room Chest','Mountain Path'),
    LocationDef(4560012, '(MP) Platform Warp Room Chest','Mountain Path'),
    LocationDef(4560013, '(MP) Warp Room Behind Vines (1)','Mountain Path'),
    LocationDef(4560013, '(MP) Warp Room Behind Vines (2)','Mountain Path'),
    LocationDef(4560015, '(MP) East of Crystal Room - Ledge Chest', 'Mountain Path'),
    LocationDef(4560016, '(MP) East of Crystal Room - Breakable Wall Chest', 'Mountain Path'),
    LocationDef(4560017, '(MP) Catzerker Ledge Chest', 'Mountain Path'),
    LocationDef(4560018, '(MP) Music Wall Chest', 'Mountain Path'),
    LocationDef(4560019, '(MP) West Corridor', 'Mountain Path'),
    LocationDef(4560020, '(MP) West Vertical 2', 'Mountain Path'),
    LocationDef(4560021, '(MP) West Vertical 1', 'Mountain Path'),
    LocationDef(4560022, '(MP) Northwest Cliffs 1', 'Mountain Path'),
    LocationDef(4560023, '(MP) Northwest Cliffs 2', 'Mountain Path'),
    LocationDef(4560024, '(MP) East of Buran - Chest 2', 'Mountain Path'),
    LocationDef(4560025, '(MP) East of Buran - Chest 1', 'Mountain Path'),
    LocationDef(4560026, '(MP) East of Buran - Ledge Chest', 'Mountain Path'),
    LocationDef(4560027, '(MP) East Blue Cave Shortcut', 'Mountain Path'),
    LocationDef(4560028, '(MP) Fire Orb Chest', 'Mountain Path'),
    LocationDef(4560029, '(MP) Water Orb Chest', 'Mountain Path'),
    LocationDef(4560030, '(MP) East Blue Cave Shortcut - Upper Chest', 'Mountain Path'),
    LocationDef(4560031, '(MP) West Hidden Area', 'Mountain Path'),
    LocationDef(4560032, '(MP) Monk Room', 'Mountain Path'),
    LocationDef(4560033, '(MP) Snowy Peaks Entrance', 'Mountain Path'),
    LocationDef(4560034, '(MP) North Hidden Area', 'Mountain Path'),
    LocationDef(4560035, '(MP) Manticorb Room', 'Mountain Path'),
    LocationDef(4560036, '(MP) Narrow Corridor Room', 'Mountain Path'),
    LocationDef(4570001, '(KS) West Towers', 'Keeper Stronghold'),
    LocationDef(4570002, '(KS) West Stairs', 'Keeper Stronghold'),
    LocationDef(4570003, '(KS) Storage 1', 'Keeper Stronghold'),
    LocationDef(4570004, '(KS) Storage 2', 'Keeper Stronghold'),
    LocationDef(4570005, '(EE) Eternity\'s End - Chest 2', 'Keeper Stronghold'),
    LocationDef(4570006, '(EE) Eternity\'s End - Chest 1', 'Keeper Stronghold'),
    LocationDef(4580001, '(BC) Platforms - Breakable Wall Chest', 'Blue Cave'),
    LocationDef(4580002, '(BC) Platforms - Special Chest', 'Blue Cave'),
    LocationDef(4580003, '(BC) Platforms - Ledge Chest', 'Blue Cave'),
    LocationDef(4580004, '(BC) North Fork - East Ledge Chest', 'Blue Cave'),
    LocationDef(4580005, '(BC) North Fork', 'Blue Cave'),
    LocationDef(4580006, '(BC) North Fork - Ground Switch Chest', 'Blue Cave'),
    LocationDef(4580007, '(BC) North Fork - Nook Chest', 'Blue Cave'),
    LocationDef(4580008, '(BC) Central West Corridor 1', 'Blue Cave'),
    LocationDef(4580009, '(BC) Central West Corridor 2', 'Blue Cave'),
    LocationDef(4580010, '(BC) East 2', 'Blue Cave'),
    LocationDef(4580011, '(BC) East 1', 'Blue Cave'),
    LocationDef(4580012, '(BC) Upper South Vertical', 'Blue Cave'),
    LocationDef(4580013, '(BC) Double Jump Boots Chest', 'Blue Cave'),
    LocationDef(4580014, '(BC) South Big Rock Room', 'Blue Cave'),
    LocationDef(4580015, '(BC) Lower South Vertical', 'Blue Cave'),
    LocationDef(4580016, '(BC) South Jump Puzzle Room 1', 'Blue Cave'),
    LocationDef(4580017, '(BC) South Jump Puzzle Room 2', 'Blue Cave'),
    LocationDef(4580018, '(BC) Crystal Room - Middle Ledge Chest', 'Blue Cave'),
    LocationDef(4580019, '(BC) Crystal Room - Upper Ledge Chest 2', 'Blue Cave'),
    LocationDef(4580020, '(BC) Crystal Room - Upper Ledge Chest 1', 'Blue Cave'),
    LocationDef(4580021, '(BC) East 4', 'Blue Cave'),
    LocationDef(4580022, '(BC) East 3', 'Blue Cave'),
    LocationDef(4580023, '(BC) Chains 1', 'Blue Cave'),
    LocationDef(4580024, '(BC) Chains 2', 'Blue Cave'),
    LocationDef(4580025, '(BC) West Vertical', 'Blue Cave'),
    LocationDef(4580026, '(BC) West Waters - Breakable Walls Chest', 'Blue Cave'),
    LocationDef(4580027, '(BC) West Waters - Ledge Chest', 'Blue Cave'),
    LocationDef(4580028, '(BC) Specter Room', 'Blue Cave'),
    LocationDef(4580029, '(BC) Levitate Room 1', 'Blue Cave'),
    LocationDef(4580030, '(BC) Levitate Room 2', 'Blue Cave'),
    LocationDef(4580031, '(BC) Sun Palace Entrance - Ledge Chest', 'Blue Cave'),
    LocationDef(4580032, '(BC) Sun Palace Entrance - Switch Puzzle Chest', 'Blue Cave'),
    LocationDef(4580033, '(BC) Central East Corridor 3', 'Blue Cave'),
    LocationDef(4580034, '(BC) Central Hidden Area', 'Blue Cave'),
    LocationDef(4580035, '(BC) Specter Hallway - Earth Orb Chest', 'Blue Cave'),
    LocationDef(4580036, '(BC) Specter Hallway - Lightning Orb Chest', 'Blue Cave'),
    LocationDef(4590001, '(SD) Jail - Chest', 'Stronghold Dungeon'),
    LocationDef(4590002, '(SD) Jail - Switches Chest', 'Stronghold Dungeon'),
    LocationDef(4590003, '(SD) Jail Hidden Area', 'Stronghold Dungeon'),
    LocationDef(4590004, '(SD) North Vertical', 'Stronghold Dungeon'),
    LocationDef(4590005, '(SD) North Dark Room', 'Stronghold Dungeon'),
    LocationDef(4590006, '(SD) North Vertical - Lightning Orb Chest', 'Stronghold Dungeon'),
    LocationDef(4590007, '(SD) West Corridor - Heavy Block', 'Stronghold Dungeon'),
    LocationDef(4590008, '(SD) West Corridor - Breakable Wall', 'Stronghold Dungeon'),
    LocationDef(4590009, '(SD) Gates Puzzle Room - Upper Ledge', 'Stronghold Dungeon'),
    LocationDef(4590010, '(SD) Gates Puzzle Room - Middle Ledge', 'Stronghold Dungeon'),
    LocationDef(4590011, '(SD) Big Rock Room 3', 'Stronghold Dungeon'),
    LocationDef(4590012, '(SD) Big Rock Room 2', 'Stronghold Dungeon'),
    LocationDef(4590013, '(SD) Big Rock Room 1', 'Stronghold Dungeon'),
    LocationDef(4590014, '(SD) Big Rock Room - Behind Gate', 'Stronghold Dungeon'),
    LocationDef(4590015, '(SD) West Sewer', 'Stronghold Dungeon'),
    LocationDef(4590016, '(SD) West Hidden - Nook', 'Stronghold Dungeon'),
    LocationDef(4590017, '(SD) West Hidden - Breakable Wall', 'Stronghold Dungeon'),
    LocationDef(4590018, '(SD) East Sewer - Southwest Ledge', 'Stronghold Dungeon'),
    LocationDef(4590019, '(SD) East Sewer - Key Door Chest', 'Stronghold Dungeon'),
    LocationDef(4590020, '(SD) East Sewer - Central Ledge', 'Stronghold Dungeon'),
    LocationDef(4590021, '(SD) Slime Statue Room 2', 'Stronghold Dungeon'),
    LocationDef(4590022, '(SD) Slime Statue Room 1', 'Stronghold Dungeon'),
    LocationDef(4590023, '(SD) Ice Orb Chest', 'Stronghold Dungeon'),
    LocationDef(4590024, '(SD) East Dark Corridor', 'Stronghold Dungeon'),
    LocationDef(4590025, '(SD) East Lever Puzzle', 'Stronghold Dungeon'),
    LocationDef(4590026, '(SD) Central Dark Room', 'Stronghold Dungeon'),
    LocationDef(4590027, '(SD) Lower Ancient Woods Entrance', 'Stronghold Dungeon'),
    LocationDef(4590028, '(SD) Ancient Woods Entrance', 'Stronghold Dungeon'),
    LocationDef(4590029, '(SD) After Library Key Door', 'Stronghold Dungeon'),
    LocationDef(4590030, '(SD) West Vertical', 'Stronghold Dungeon'),
    LocationDef(4590031, '(SD) Workshop Entrance', 'Stronghold Dungeon'),
    LocationDef(4590032, '(SD) Library Hidden Area 1', 'Stronghold Dungeon'),
    LocationDef(4590033, '(SD) Library Hidden Area 2', 'Stronghold Dungeon'),
    LocationDef(4600001, '(AW) West Deep Caves - Spike Jump Chest', 'Ancient Woods'),
    LocationDef(4600002, '(AW) Dark Caves - Torches Chest', 'Ancient Woods'),
    LocationDef(4600003, '(AW) West Deep Caves - Vines Chest', 'Ancient Woods'),
    LocationDef(4600004, '(AW) West Deep Caves Spike Room', 'Ancient Woods'),
    LocationDef(4600005, '(AW) Door Puzzle 2', 'Ancient Woods'),
    LocationDef(4600006, '(AW) Door Puzzle 3', 'Ancient Woods'),
    LocationDef(4600007, '(AW) Door Puzzle 1', 'Ancient Woods'),
    LocationDef(4600008, '(AW) West Pit - West Chest', 'Ancient Woods'),
    LocationDef(4600009, '(AW) West Pit - East Chest', 'Ancient Woods'),
    LocationDef(4600010, '(AW) Tree of Evolution Chest', 'Ancient Woods'),
    LocationDef(4600011, '(AW) East - Scaffold Chest 1', 'Ancient Woods'),
    LocationDef(4600012, '(AW) West Caves - Breakable Wall', 'Ancient Woods'),
    LocationDef(4600013, '(AW) West Caves - High Ledge', 'Ancient Woods'),
    LocationDef(4600014, '(AW) West Jump Puzzle 1', 'Ancient Woods'),
    LocationDef(4600015, '(AW) West Jump Puzzle 2', 'Ancient Woods'),
    LocationDef(4600016, '(AW) West Cliffs', 'Ancient Woods'),
    LocationDef(4600017, '(AW) Upper Dungeon Entrance', 'Ancient Woods'),
    LocationDef(4600018, '(AW) East - Scaffold Chest 2', 'Ancient Woods'),
    LocationDef(4600019, '(AW) North - West Key Chest', 'Ancient Woods'),
    LocationDef(4600020, '(AW) North - Goblin King Chest 1', 'Ancient Woods'),
    LocationDef(4600021, '(AW) North - Goblin King Chest 2', 'Ancient Woods'),
    LocationDef(4600022, '(AW) East - Goblin King Shortcut Chest', 'Ancient Woods'),
    LocationDef(4600023, '(AW) East - Lightning Orb Chest', 'Ancient Woods'),
    LocationDef(4600024, '(AW) South Dark Room', 'Ancient Woods'),
    LocationDef(4600025, '(AW) Torches Room 2', 'Ancient Woods'),
    LocationDef(4600026, '(AW) Torches Room 1', 'Ancient Woods'),
    LocationDef(4600027, '(AW) South Glowfly Room 1', 'Ancient Woods'),
    LocationDef(4600028, '(AW) South Glowfly Room 2', 'Ancient Woods'),
    LocationDef(4600029, '(AW) West Deep Caves - Dark Room', 'Ancient Woods'),
    LocationDef(4600030, '(AW) West Deep Caves - Spike Fall Chest 2', 'Ancient Woods'),
    LocationDef(4600031, '(AW) West Deep Caves - Spike Fall Chest 1', 'Ancient Woods'),
    LocationDef(4600032, '(AW) Upper East - Chest 1', 'Ancient Woods'),
    LocationDef(4600033, '(AW) Upper East - Chest 2', 'Ancient Woods'),
    LocationDef(4600034, '(AW) Upper East - Grapple Chest', 'Ancient Woods'),
    LocationDef(4600035, '(AW) South - Back of Brutus', 'Ancient Woods'),
    LocationDef(4600036, '(AW) Dark Caves - Vertical Shaft', 'Ancient Woods'),
    LocationDef(4600037, '(AW) West Deep Caves - Spore Shroud Chest', 'Ancient Woods'),
    LocationDef(4610001, '(SNP) East - Breakable Wall Chest', 'Snowy Peaks'),
    LocationDef(4610002, '(SNP) East - Ledge Chest', 'Snowy Peaks'),
    LocationDef(4610003, '(SNP) East - Floating Platform Chest', 'Snowy Peaks'),
    LocationDef(4610004, '(SNP) East Cave - Upper Lever Chest', 'Snowy Peaks'),
    LocationDef(4610005, '(SNP) East Cave - Lower Lever Chest', 'Snowy Peaks'),
    LocationDef(4610006, '(SNP) East Cave - Middle Chest', 'Snowy Peaks'),
    LocationDef(4610007, '(SNP) East Hills - Breakable Walls Chest', 'Snowy Peaks'),
    LocationDef(4610008, '(SNP) East Spikes', 'Snowy Peaks'),
    LocationDef(4610009, '(SNP) West Cave - Ice Orb Chest', 'Snowy Peaks'),
    LocationDef(4610010, '(SNP) West Cave - Middle Chest', 'Snowy Peaks'),
    LocationDef(4610011, '(SNP) West Cave - Upper Chest', 'Snowy Peaks'),
    LocationDef(4610012, '(SNP) Dracozul Climb - Lower Chest', 'Snowy Peaks'),
    LocationDef(4610013, '(SNP) Dracozul Climb - Upper Chest', 'Snowy Peaks'),
    LocationDef(4610014, '(SNP) West Cave - Earth Orb Chest', 'Snowy Peaks'),
    LocationDef(4610015, '(SNP) West Mountain - Western Chest', 'Snowy Peaks'),
    LocationDef(4610016, '(SNP) West Mountain - Ice Orb Chest', 'Snowy Peaks'),
    LocationDef(4610017, '(SNP) West Mountain - Diamond Block Chest', 'Snowy Peaks'),
    LocationDef(4610018, '(SNP) West Mountain Peak - Ledge Chest', 'Snowy Peaks'),
    LocationDef(4610019, '(SNP) West Mountain Peak - Hidden Area Chest', 'Snowy Peaks'),
    LocationDef(4610020, '(SNP) East Mountain Peak - Cave Chest', 'Snowy Peaks'),
    LocationDef(4610021, '(SNP) East Mountain Peak - Floating Ledge Chest', 'Snowy Peaks'),
    LocationDef(4610022, '(SNP) East Mountain - Lightning Orb Chest', 'Snowy Peaks'),
    LocationDef(4610023, '(SNP) East Mountain - East Lower Chest', 'Snowy Peaks'),
    LocationDef(4610024, '(SNP) East Mountain - Upper Crumble Ledge Chest 1', 'Snowy Peaks'),
    LocationDef(4610025, '(SNP) East Mountain - Lower Crumble Ledge Chest 2', 'Snowy Peaks'),
    LocationDef(4610026, '(SNP) East Mountain - Underwater Chest', 'Snowy Peaks'),
    LocationDef(4610027, '(SNP) East Mountain - Crumble Platform Challenge Chest', 'Snowy Peaks'),
    LocationDef(4610028, '(SNP) East Mountain - Water Orb Chest', 'Snowy Peaks'),
    LocationDef(4610029, '(SNP) East Mountain - Upper Cave Chest', 'Snowy Peaks'),
    LocationDef(4610030, '(SNP) East Mountain - West Crumble Ledge Chest', 'Snowy Peaks'),
    LocationDef(4610031, '(SNP) East Mountain - Spikes Chest', 'Snowy Peaks'),
    LocationDef(4610032, '(SNP) East Mountain Peak - Peak Chest', 'Snowy Peaks'),
    LocationDef(4610033, '(SNP) West Mountain - Eastern Chest', 'Snowy Peaks'),
    LocationDef(4610034, '(SNP) West Hills', 'Snowy Peaks'),
    LocationDef(4610035, '(SNP) Lake - Underwater Chest', 'Snowy Peaks'),
    LocationDef(4610036, '(SNP) Lake - West Chest 2', 'Snowy Peaks'),
    LocationDef(4610037, '(SNP) Lake - West Chest 1', 'Snowy Peaks'),
    LocationDef(4610038, '(SNP) Akhlut Room Chest', 'Snowy Peaks'),
    LocationDef(4610039, '(SNP) West Dark Room', 'Snowy Peaks'),
    LocationDef(4620001, '(SUN) West - Upper Interior Chest', 'Sun Palace'),
    LocationDef(4620002, '(SUN) West - Lower Interior Chest', 'Sun Palace'),
    LocationDef(4620003, '(SUN) West - Floating Ledge Chest', 'Sun Palace'),
    LocationDef(4620004, '(SUN) West - Mount Door Chest', 'Sun Palace'),
    LocationDef(4620005, '(SUN) South - Fire Orb Chest', 'Sun Palace'),
    LocationDef(4620006, '(SUN) South - Ice Orb Chest', 'Sun Palace'),
    LocationDef(4620007, '(SUN) Central Sewer - Upper Chest', 'Sun Palace'),
    LocationDef(4620008, '(SUN) Central Sewer - Middle East Chest', 'Sun Palace'),
    LocationDef(4620009, '(SUN) Central Sewer - Middle West Chest', 'Sun Palace'),
    LocationDef(4620010, '(SUN) Central Sewer - Central Chest', 'Sun Palace'),
    LocationDef(4620011, '(SUN) Central Sewer - Lower East Chest', 'Sun Palace'),
    LocationDef(4620012, '(SUN) East Sewers - Timed Jump Chest', 'Sun Palace'),
    LocationDef(4620013, '(SUN) East - Door Chest', 'Sun Palace'),
    LocationDef(4620014, '(SUN) East - Lever Chest', 'Sun Palace'),
    LocationDef(4620015, '(SUN) Blue Cave Entrance 1', 'Sun Palace'),
    LocationDef(4620016, '(SUN) Blue Cave Entrance 2', 'Sun Palace'),
    LocationDef(4620017, '(SUN) Blue Cave Entrance 3', 'Sun Palace'),
    LocationDef(4620018, '(SUN) East - Interior Chest', 'Sun Palace'),
    LocationDef(4620019, '(SUN) East - Water Orb Chest', 'Sun Palace'),
    LocationDef(4620020, '(SUN) Crystal Room', 'Sun Palace'),
    LocationDef(4620021, '(SUN) West Sewers - Heavy Block Chest', 'Sun Palace'),
    LocationDef(4620022, '(SUN) West Sewers - Maze Chest 1', 'Sun Palace'),
    LocationDef(4620023, '(SUN) West Sewers - Maze Chest 2', 'Sun Palace'),
    LocationDef(4620024, '(SUN) West Sewers West Hidden Area 1', 'Sun Palace'),
    LocationDef(4620025, '(SUN) West Sewers West Hidden Area 2', 'Sun Palace'),
    LocationDef(4620026, '(SUN) West Pool - Water Chest', 'Sun Palace'),
    LocationDef(4620027, '(SUN) West Pool - Upper Chest', 'Sun Palace'),
    LocationDef(4620028, '(SUN) West Pool - Platform Chest', 'Sun Palace'),
    LocationDef(4620029, '(SUN) Slime Statue Room - Center Chest', 'Sun Palace'),
    LocationDef(4620030, '(SUN) Slime Statue Room - Switch Chest', 'Sun Palace'),
    LocationDef(4620031, '(SUN) West Sewers East Hidden Area', 'Sun Palace'),
    LocationDef(4630001, '(MC) Crumbling Bridge', 'Magma Chamber'),
    LocationDef(4630002, '(MC) West - Vertical Shaft Chest', 'Magma Chamber'),
    LocationDef(4630003, '(MC) West - Floor Chest', 'Magma Chamber'),
    LocationDef(4630004, '(MC) Rock Pedestal Room', 'Magma Chamber'),
    LocationDef(4630005, '(MC) Center Shortcut - West', 'Magma Chamber'),
    LocationDef(4630006, '(MC) Center Shortcut - East', 'Magma Chamber'),
    LocationDef(4630007, '(MC) West - Ledge Chest', 'Magma Chamber'),
    LocationDef(4630008, '(MC) West - Dark Breakable Wall Chest', 'Magma Chamber'),
    LocationDef(4630009, '(MC) North - Lever Puzzle', 'Magma Chamber'),
    LocationDef(4630010, '(MC) North - West Ledge Chest', 'Magma Chamber'),
    LocationDef(4630011, '(MC) Ancient Woods Entrance', 'Magma Chamber'),
    LocationDef(4630012, '(MC) North - Dark Room', 'Magma Chamber'),
    LocationDef(4630013, '(MC) East - Floor Chest', 'Magma Chamber'),
    LocationDef(4630014, '(MC) East - Behind Diamond Block', 'Magma Chamber'),
    LocationDef(4630015, '(MC) Lava Pillars', 'Magma Chamber'),
    LocationDef(4630016, '(MC) Gryphonix Room 2', 'Magma Chamber'),
    LocationDef(4630017, '(MC) Gryphonix Room 1', 'Magma Chamber'),
    LocationDef(4630018, '(MC) South Vertical Shaft - Middle Chest', 'Magma Chamber'),
    LocationDef(4630019, '(MC) South Vertical Shaft - Grapple Chest', 'Magma Chamber'),
    LocationDef(4630020, '(MC) South Vertical Shaft - Lower Chest', 'Magma Chamber'),
    LocationDef(4630021, '(MC) Center - South Shortcut Room', 'Magma Chamber'),
    LocationDef(4630022, '(MC) Tar Pit', 'Magma Chamber'),
    LocationDef(4630023, '(MC) Asura Room', 'Magma Chamber'),  
    LocationDef(4630024, '(MC) Center - Crumble Bridge Room', 'Magma Chamber'),
    LocationDef(4630025, '(MC) Center - Diamond Block Chest', 'Magma Chamber'),
    LocationDef(4630026, '(MC) East - Vertical Shaft Chest', 'Magma Chamber'),
    LocationDef(4630027, '(MC) Center - Below Lava Pit', 'Magma Chamber'),
    LocationDef(4630028, '(MC) Lava Pit - Lower Chest', 'Magma Chamber'),
    LocationDef(4630029, '(MC) Lava Pit - Middle Chest', 'Magma Chamber'),
    LocationDef(4630030, '(MC) Center - Invisible Platform Chest 1', 'Magma Chamber'),
    LocationDef(4630031, '(MC) Center - Invisible Platform Chest 2', 'Magma Chamber'),
    LocationDef(4630032, '(MC) Center - Lava Puddle Chest', 'Magma Chamber'),
    LocationDef(4630033, '(MC) Forgotten World Exit - Crumble Bridge Chest', 'Magma Chamber'),
    LocationDef(4630034, '(MC) Forgotten World Exit - Hidden Chest 1', 'Magma Chamber'),
    LocationDef(4630035, '(MC) Forgotten World Exit - Hidden Chest 2', 'Magma Chamber'),
    LocationDef(4630036, '(MC) Forgotten World Exit', 'Magma Chamber'),
    LocationDef(4630037, '(MC) Crumble Bridge Puzzle - Lower Chest', 'Magma Chamber'),
    LocationDef(4630038, '(MC) Crumble Bridge Puzzle - Upper Chest', 'Magma Chamber'),
    LocationDef(4640001, '(FW) Magma Chamber Entrance', 'Forgotten World'),
    LocationDef(4640002, '(FW) North Caves - Diamond Block Stack', 'Forgotten World'),
    LocationDef(4640003, '(FW) West Caves - Levitate Chest', 'Forgotten World'),
    LocationDef(4640004, '(FW) Caves Study', 'Forgotten World'),  
    LocationDef(4640005, '(FW) South Caves Tunnel - Magic Vines Chest', 'Forgotten World'),
    LocationDef(4640006, '(FW) Magic Vine Maze - Lower Chest', 'Forgotten World'),
    LocationDef(4640007, '(FW) Magic Vine Maze - Middle Chest', 'Forgotten World'),
    LocationDef(4640008, '(FW) Magic Vine Maze - Upper Chest', 'Forgotten World'),
    LocationDef(4640009, '(FW) North Caves Vertical', 'Forgotten World'),
    LocationDef(4640010, '(FW) West Jungle - Lower Chest', 'Forgotten World'),
    LocationDef(4640011, '(FW) West Jungle - Upper Chest', 'Forgotten World'),
    LocationDef(4640012, '(FW) North East Tar Pits', 'Forgotten World'),
    LocationDef(4640013, '(FW) East Tar Pits Vertical - Upper Chest', 'Forgotten World'),
    LocationDef(4640014, '(FW) East Tar Pits Vertical - Lower Chest', 'Forgotten World'),
    LocationDef(4640015, '(FW) East Tar Pits Corridor - West Chest', 'Forgotten World'),  
    LocationDef(4640016, '(FW) North West Tar Pits', 'Forgotten World'),
    LocationDef(4640017, '(FW) Crystal Room', 'Forgotten World'),
    LocationDef(4640018, '(FW) East Caves Large Room - NE Chest', 'Forgotten World'),
    LocationDef(4640019, '(FW) East Caves Large Room - West Chest', 'Forgotten World'),
    LocationDef(4640020, '(FW) South Caves Dark Room', 'Forgotten World'),
    LocationDef(4640021, '(FW) South Waters Vertical - Upper Chest', 'Forgotten World'),
    LocationDef(4640022, '(FW) South Waters - Currents Chest', 'Forgotten World'),
    LocationDef(4640023, '(FW) South Waters - Cave Chest', 'Forgotten World'),
    LocationDef(4640024, '(FW) Dracomer Lair', 'Forgotten World'),
    LocationDef(4640025, '(FW) South Waters - Magic Walls Chest', 'Forgotten World'),
    LocationDef(4640026, '(FW) South Waters - Dual Mobility Chest', 'Forgotten World'),
    LocationDef(4640027, '(FW) West Tar Pits Vertical', 'Forgotten World'),
    LocationDef(4640028, '(FW) South West Tar Pits', 'Forgotten World'),
    LocationDef(4640029, '(FW) Descent Hidden Room 3', 'Forgotten World'),
    LocationDef(4640030, '(FW) Descent Hidden Room 2', 'Forgotten World'),
    LocationDef(4640031, '(FW) Descent Hidden Room 1', 'Forgotten World'),
    LocationDef(4640032, '(FW) Terradrile Lair - West Chest', 'Forgotten World'),
    LocationDef(4640033, '(FW) Terradrile Lair - East Chest', 'Forgotten World'),
    LocationDef(4640034, '(FW) Terradrile Lair Vertical', 'Forgotten World'),
    LocationDef(4640035, '(FW) Center Caves - Magic Wall Chest', 'Forgotten World'),
    LocationDef(4640036, '(FW) East Jungle - Beneath Mushrooms', 'Forgotten World'),
    LocationDef(4640037, '(FW) East Jungle - High Ledge Chest', 'Forgotten World'),
    LocationDef(4640038, '(FW) East Jungle - Invisible Platform Chest', 'Forgotten World'),
    LocationDef(4640039, '(FW) East Jungle - Magic Vines Chest', 'Forgotten World'),
    LocationDef(4640040, '(FW) South Climb - Vines Chest', 'Forgotten World'),
    LocationDef(4640041, '(FW) South Climb - Puzzle Chest', 'Forgotten World'),
    LocationDef(4640042, '(FW) South Climb - Special Chest', 'Forgotten World'),  
    LocationDef(4640043, '(FW) Vertical Climb - Lower Chest', 'Forgotten World'),
    LocationDef(4640044, '(FW) Vertical Climb - Middle Chest', 'Forgotten World'),
    LocationDef(4640045, '(FW) Vertical Climb - Upper Chest', 'Forgotten World'),
    LocationDef(4640046, '(FW) North East Climb', 'Forgotten World'),
    LocationDef(4640047, '(FW) North Center Climb - SE Chest', 'Forgotten World'),
    LocationDef(4640048, '(FW) North Center Climb - SW Chest 2', 'Forgotten World'),
    LocationDef(4640049, '(FW) North Center Climb NW Chest', 'Forgotten World'),
    LocationDef(4640050, '(FW) North Center Climb - Diamond Blocks 2', 'Forgotten World'),
    LocationDef(4640051, '(FW) North Center Climb - Diamond Blocks 1', 'Forgotten World'),
    LocationDef(4640052, '(FW) North Center Climb - SW Chest 1', 'Forgotten World'),
    LocationDef(4640053, '(FW) North West Climb - East Chest', 'Forgotten World'),
    LocationDef(4640054, '(FW) North West Climb - Lofty Mount Chest', 'Forgotten World'),
    LocationDef(4640055, '(FW) Horizon Beach Exit', 'Forgotten World'),
    LocationDef(4640056, '(FW) Center Jungle - Crumble Bridge Chest', 'Forgotten World'),
    LocationDef(4640057, '(FW) Center Jungle - Floating Ledges Chest', 'Forgotten World'),
    LocationDef(4640058, '(FW) South Waters - Hidden Room', 'Forgotten World'),
    LocationDef(4650001, '(HB) West - Underwater Chest', 'Horizon Beach'),
    LocationDef(4650002, '(HB) West - Flying Ledges 1', 'Horizon Beach'),
    LocationDef(4650003, '(HB) West - Flying Ledges 2', 'Horizon Beach'),
    LocationDef(4650004, '(HB) West - Water Cave Chest', 'Horizon Beach'),
    LocationDef(4650005, '(HB) West - Fast Currents Chest', 'Horizon Beach'),
    LocationDef(4650006, '(HB) South - Cove Chest', 'Horizon Beach'),
    LocationDef(4650007, '(HB) Treasure Cave - Vertical Room', 'Horizon Beach'),
    LocationDef(4650008, '(HB) Treasure Cave - Web Room', 'Horizon Beach'),
    LocationDef(4650009, '(HB) Treasure Cave - Watery Tunnel', 'Horizon Beach'),
    LocationDef(4650010, '(HB) Elderjel Room - Normal Chest', 'Horizon Beach'),
    LocationDef(4650011, '(HB) Elderjel Room - Special Chest', 'Horizon Beach'),
    LocationDef(4650012, '(HB) Forgotten World Entrance', 'Horizon Beach'),
    LocationDef(4650013, '(HB) South - Spike Room 2', 'Horizon Beach'),
    LocationDef(4650014, '(HB) South - Spike Room 1', 'Horizon Beach'),
    LocationDef(4650015, '(HB) Labyrinth - Southwest Chest', 'Horizon Beach'),
    LocationDef(4650016, '(HB) Labyrinth - Southeast Chest', 'Horizon Beach'),
    LocationDef(4650017, '(HB) Central - West Shortcut Chest', 'Horizon Beach'),
    LocationDef(4650018, '(HB) Central - East Shortcut Chest', 'Horizon Beach'),
    LocationDef(4650019, '(HB) Central - Fast Currents Chest 1', 'Horizon Beach'),
    LocationDef(4650020, '(HB) Central - Fast Currents Chest 2', 'Horizon Beach'),
    LocationDef(4650021, '(HB) Central - Fast Currents Chest 3', 'Horizon Beach'),
    LocationDef(4650022, '(HB) Central - Island Chest', 'Horizon Beach'),
    LocationDef(4650023, '(HB) East - West Peak 1', 'Horizon Beach'),
    LocationDef(4650024, '(HB) East - West Peak 2', 'Horizon Beach'),
    LocationDef(4650025, '(HB) East - East Peak 1', 'Horizon Beach'),
    LocationDef(4650026, '(HB) East - East Peak 2', 'Horizon Beach'),
    LocationDef(4650027, '(HB) East - Middle Ledge Chest 1', 'Horizon Beach'),
    LocationDef(4650028, '(HB) East - Beneath Bridge', 'Horizon Beach'),
    LocationDef(4650029, '(HB) East - Middle Ledge Chest 2', 'Horizon Beach'),
    LocationDef(4650030, '(HB) East - Underwater Chest', 'Horizon Beach'),
    LocationDef(4650031, '(HB) Fisherman Chest', 'Horizon Beach'),
    LocationDef(4650032, '(HB) East - Fast Currents Tunnel', 'Horizon Beach'),
    LocationDef(4650033, '(HB) Central - Ice Orb Chest', 'Horizon Beach'),
    LocationDef(4650034, '(HB) Central - Timed Door Chest', 'Horizon Beach'),
    LocationDef(4650035, '(HB) East Hidden', 'Horizon Beach'),
    LocationDef(4650036, '(HB) Vodinoy Room 1', 'Horizon Beach'),
    LocationDef(4650037, '(HB) Vodinoy Room 2', 'Horizon Beach'),
    LocationDef(4650038, '(HB) South - Pit Secret Room', 'Horizon Beach'),
    LocationDef(4660001, '(UW) East - Catacomb Entrance', 'Underworld'),
    LocationDef(4660002, '(UW) East Catacomb - Key Chest', 'Underworld'),
    LocationDef(4660003, '(UW) East Catacomb - Beneath Pillar', 'Underworld'),
    LocationDef(4660004, '(UW) East Catacomb - Lever Room', 'Underworld'),
    LocationDef(4660005, '(UW) East Catacomb - Behind Pillar 1', 'Underworld'),
    LocationDef(4660006, '(UW) East Catacomb - Peak Chest 1', 'Underworld'),
    LocationDef(4660007, '(UW) East Catacomb - Peak Chest 2', 'Underworld'),
    LocationDef(4660008, '(UW) West Catacomb - East Basement', 'Underworld'),
    LocationDef(4660009, '(UW) West Catacomb - West Basement', 'Underworld'),
    LocationDef(4660010, '(UW) Center Cave', 'Underworld'),
    LocationDef(4660011, '(UW) West Catacomb - Hub Room', 'Underworld'),
    LocationDef(4660012, '(UW) West Catacomb - Pit', 'Underworld'),
    LocationDef(4660013, '(UW) West Catacomb - West Exterior', 'Underworld'),
    LocationDef(4660014, '(UW) Crystal Room', 'Underworld'),
    LocationDef(4660015, '(UW) West Catacomb - East Roof', 'Underworld'),
    LocationDef(4660016, '(UW) West Catacomb - West Roof', 'Underworld'),
    LocationDef(4660017, '(UW) Draconoir Room', 'Underworld'),  
    LocationDef(4660018, '(UW) West Catacomb - Roof', 'Underworld'),
    LocationDef(4660019, '(UW) Sun Palace Entrance', 'Underworld'),
    LocationDef(4660020, '(UW) Spinner Cave', 'Underworld'),
    LocationDef(4660021, '(UW) Morph Ball Room 2', 'Underworld'),
    LocationDef(4660022, '(UW) Morph Ball Room 1', 'Underworld'),
    LocationDef(4660023, '(UW) East Catacomb - Behind Pillar 2', 'Underworld'),
    LocationDef(4660024, '(UW) East Catacomb - Basement Chest 2', 'Underworld'),
    LocationDef(4660025, '(UW) East Catacomb - Basement Chest 1', 'Underworld'),
    LocationDef(4660026, '(UW) East - Big Rock Chest', 'Underworld'),
    LocationDef(4660027, '(UW) East - Floating Ledge Chest 1', 'Underworld'),
    LocationDef(4660028, '(UW) East - Floating Ledge Chest 2', 'Underworld'),
    LocationDef(4660029, '(UW) West Catacomb - Treasure Room 2', 'Underworld'),
    LocationDef(4660030, '(UW) West Catacomb - Treasure Room 1', 'Underworld'),
    LocationDef(4670001, '(MW) South - In Front of Diamond Block', 'Mystical Workshop'),
    LocationDef(4670002, '(MW) South - Behind Diamond Block', 'Mystical Workshop'),
    LocationDef(4670003, '(MW) Pipe Puzzle Room 2', 'Mystical Workshop'),
    LocationDef(4670004, '(MW) Pipe Puzzle Room 1', 'Mystical Workshop'),
    LocationDef(4670005, '(MW) Before Golem Merchant', 'Mystical Workshop'),
    LocationDef(4670006, '(MW) Abandoned Tower Entrance', 'Mystical Workshop'),
    LocationDef(4670007, '(MW) South Eastern Shaft', 'Mystical Workshop'),
    LocationDef(4670008, '(MW) South Cog Room - Lower Chest', 'Mystical Workshop'),
    LocationDef(4670009, '(MW) South Cog Room - Middle Chest', 'Mystical Workshop'),
    LocationDef(4670010, '(MW) South Cog Room - Upper Chest', 'Mystical Workshop'),
    LocationDef(4670011, '(MW) Lighting and Ice Orb Chest', 'Mystical Workshop'),
    LocationDef(4670012, '(MW) South Grapple Room - Ground Chest', 'Mystical Workshop'),
    LocationDef(4670013, '(MW) South Grapple Room - Grapple Chest', 'Mystical Workshop'),
    LocationDef(4670014, '(MW) South Pipes Room', 'Mystical Workshop'),
    LocationDef(4670015, '(MW) Timed Lever Puzzle 1', 'Mystical Workshop'),
    LocationDef(4670016, '(MW) Timed Lever Puzzle 2', 'Mystical Workshop'),
    LocationDef(4670017, '(MW) North Cog Room - West Chest', 'Mystical Workshop'),
    LocationDef(4670018, '(MW) North Cog Room - East Chest', 'Mystical Workshop'),
    LocationDef(4670019, '(MW) North Lever Puzzle', 'Mystical Workshop'),
    LocationDef(4670020, '(MW) Blob Statue Room', 'Mystical Workshop'),
    LocationDef(4670021, '(MW) Eastern Vertical', 'Mystical Workshop'),
    LocationDef(4670022, '(MW) Clock Room', 'Mystical Workshop'),
    LocationDef(4670023, '(MW) North Shortcut Door', 'Mystical Workshop'),
    LocationDef(4670024, '(MW) Goblin Pilot Room', 'Mystical Workshop'),
    LocationDef(4670025, '(MW) Mimic Room', 'Mystical Workshop'),
    LocationDef(4670026, '(MW) Lower Vat Room 2', 'Mystical Workshop'),
    LocationDef(4670027, '(MW) Lower Vat Room 1', 'Mystical Workshop'),
    LocationDef(4670028, '(MW) Upper Vat Room', 'Mystical Workshop'),
    LocationDef(4670029, '(MW) Hidden Clock Room', 'Mystical Workshop'),
    LocationDef(4670030, '(MW) Hidden Clock Room - Levitate Chest 2', 'Mystical Workshop'),
    LocationDef(4670031, '(MW) Hidden Clock Room - Levitate Chest 1', 'Mystical Workshop'),
    LocationDef(4670032, '(MW) South - Hidden Room', 'Mystical Workshop'),
    LocationDef(4680001, '(AT) South Water Orb Chest', 'Abandoned Tower'),
    LocationDef(4680002, '(AT) South Grapple Chest', 'Abandoned Tower'),
    LocationDef(4680003, '(AT) South Big Rock Chest', 'Abandoned Tower'),
    LocationDef(4680004, '(AT) South Fire Orb Chest', 'Abandoned Tower'),
    LocationDef(4680005, '(AT) South Breakable Walls Chest', 'Abandoned Tower'),
    LocationDef(4680006, '(AT) South East Climb', 'Abandoned Tower'),
    LocationDef(4680007, '(AT) Center Lightning Orb Chest', 'Abandoned Tower'),
    LocationDef(4680008, '(AT) Center Diamond Chest', 'Abandoned Tower'),
    LocationDef(4680009, '(AT) Center Switch Chest 2', 'Abandoned Tower'),
    LocationDef(4680010, '(AT) Center Switch Chest 1', 'Abandoned Tower'),
    LocationDef(4680011, '(AT) South Square Room - Double Jump Chest', 'Abandoned Tower'),
    LocationDef(4680012, '(AT) South Square Room - Upper Chest', 'Abandoned Tower'),
    LocationDef(4680013, '(AT) Center Timed Chest', 'Abandoned Tower'),
    LocationDef(4680014, '(AT) Center East Side', 'Abandoned Tower'),
    LocationDef(4680015, '(AT) Center Dark Room - Upper Chest', 'Abandoned Tower'),
    LocationDef(4680016, '(AT) Center Dark Room - Lower Chest', 'Abandoned Tower'),
    LocationDef(4680017, '(AT) Center - Underwater Chest', 'Abandoned Tower'),
    LocationDef(4680018, '(AT) Crystal Room', 'Abandoned Tower'),
    LocationDef(4680019, '(AT) North Ice Orb Chest', 'Abandoned Tower'),
    LocationDef(4680020, '(AT) North Earth Orb Chest', 'Abandoned Tower'),
    LocationDef(4680021, '(AT) North East Side', 'Abandoned Tower'),
    LocationDef(4680022, '(AT) East Invisible Platform Chest', 'Abandoned Tower'),
    LocationDef(4680023, '(AT) North Hidden Room 1', 'Abandoned Tower'),
    LocationDef(4680024, '(AT) North Hidden Room 2', 'Abandoned Tower'),
    LocationDef(4680025, '(AT) Center Lofty Mount Chest', 'Abandoned Tower'),
    LocationDef(4680026, '(AT) South Morph Ball Room 1', 'Abandoned Tower'),
    LocationDef(4680027, '(AT) South Morph Ball Room 2', 'Abandoned Tower'),
    LocationDef(4680028, '(AT) South Hidden Room', 'Abandoned Tower'),
    LocationDef(4690001, '(BB) North East Vertical', 'Blob Burg'),
    LocationDef(4690002, '(BB) North Morph Ball Tunnel', 'Blob Burg'),
    LocationDef(4690003, '(BB) North East Tunnel', 'Blob Burg'),
    LocationDef(4690004, '(BB) Center Vertical', 'Blob Burg'),
    LocationDef(4690005, '(BB) Center Tunnel 1', 'Blob Burg'),
    LocationDef(4690006, '(BB) Center Tunnel 2', 'Blob Burg'),  
    LocationDef(4690007, '(BB) South East Vertical', 'Blob Burg'),
    LocationDef(4690008, '(BB) South East Tunnel', 'Blob Burg'),  
    LocationDef(4690009, '(BB) North Center Tunnel', 'Blob Burg'),  
    LocationDef(4690010, '(BB) Crystal Room', 'Blob Burg'),
    LocationDef(4690011, '(BB) South Room - Upper Chest', 'Blob Burg'),  
    LocationDef(4690012, '(BB) South Room - Levitate Chest', 'Blob Burg'),
    LocationDef(4690013, '(BB) South Room - Underwater Chest', 'Blob Burg'),
    LocationDef(4690014, '(BB) West Room - Eastern Chest', 'Blob Burg'),
    LocationDef(4690015, '(BB) West Room - Center Chest 2', 'Blob Burg'),
    LocationDef(4690016, '(BB) West Room - Morph Ball Chest', 'Blob Burg'),
    LocationDef(4690017, '(BB) West Tower', 'Blob Burg'),  
    LocationDef(4690018, '(BB) King Blob Room', 'Blob Burg'),  
    LocationDef(4690019, '(BB) Worm Room - Lower Chest', 'Blob Burg'),
    LocationDef(4690020, '(BB) Worm Room - Upper Chest', 'Blob Burg'),
]
